.TH CHRONOMODEL 1 "24 Sep 2024" "Chronomodel" "Utilitaires"

.SH NAME
chronomodel - un utilitaire pour gérer les modèles de chronologie

.SH DESCRIPTION
chronomodel est un utilitaire qui permet de gérer les modèles de chronologie.

.SH EXAMPLES
chronomodel -h
chronomodel -v
chronomodel modele

.SH SEE ALSO
chronomodel(5)

