#ifndef DATATIONC14_GLOBAL_H
#define DATATIONC14_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATATIONC14_LIBRARY)
#  define DATATIONC14SHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATATIONC14SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATATIONC14_GLOBAL_H
